name: tarot_proxy_server
description: >
  A lightweight and secure proxy server written in Dart.
  Designed for the Tarot MiniApp to relay API requests with Basic Auth,
  while enabling safe access from the browser via CORS.
version: 1.0.0
repository: https://github.com/ilbagatto/tarot_proxy_server.git
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  shelf: ^1.4.0
  http: ^1.2.0
  dotenv: ^4.2.0
  logger: ^2.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mocktail: ^1.0.0
