name: tarot_proxy_server
description: A minimal Dart proxy server for securely exposing Tarot API to Telegram MiniApps via HTTPS with authentication and CORS support.
version: 1.0.0
repository: https://github.com/ilbagatto/tarot_proxy_server.git

environment:
  sdk: ^3.7.2

dependencies:
  shelf: ^1.4.0
  http: ^1.2.0
  dotenv: ^4.2.0
  logger: ^2.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mocktail: ^1.0.0
